language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
 - pear install PHP_CodeSniffer
 - phpenv rehash

script:
 - phpcs --standard=PSR2 src/ tests/
 - phpunit --coverage-text
