language: php

sudo: false

php:
 - 5.6
 - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
 - bash -c 'if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'
 - composer self-update
 - composer require "squizlabs/php_codesniffer=*"
 - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - bash -c 'vendor/bin/phpcs --standard=PSR2 src/ tests/'
 - vendor/bin/phpunit --coverage-text
 - make cs_dry_run

addons:
 apt:
  packages:
   - p7zip-full

before_deploy:
 - bash build.sh
 - 7z a -tzip shariff-backend-php.zip ./build/*
 - 7z a -ttar -so shariff-backend-php.tar ./build/* | 7z a -si shariff-backend-php.tar.gz

deploy:
  provider: releases
  api_key:
    secure: jbEPfD2xopoDQBGTJsrGvwhvb5MZislQowvHtsJ7f+B9seS9FGVc8Yq2kcqGX+8I8DyI5RCu3UlorGVnOQrxT9yxHVEK8PGjqOSCgRZw8p3jZmoNzrN7Qi+5YjCXxrAEKbT0nFYvis1DJqbuLOOU9+DBP6JWKmYvrtCjNSIxRIY=
  file:
   - shariff-backend-php.zip
   - shariff-backend-php.tar.gz
  skip_cleanup: true
  on:
    repo: heiseonline/shariff-backend-php
    tags: true
    php: 5.6
